# Generated by Django 3.2 on 2021-05-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='row',
            field=models.IntegerField(),
        ),
    ]
