# Generated by Django 3.2 on 2021-05-23 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amra', '0002_alter_seat_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='seat',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_number',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_row',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='theatre',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='amra.theatre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='seat_row_count',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='seats_in_row',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
    ]
